snscrape

Ref: https://github.com/JustAnotherArchivist/snscrape

In [2]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

Scraping tweets from a text search query

Using the code below, we are scraping 100 tweets between June 14, 2020, and August 31, 2021,
with the keywords 'SSR Bollywood'.

I then pulled attributes DateTime, tweet id, text, and username from the tweet objects.

In [3]:
# Creating list to append tweet data to
tweets_list2 = []

# search terms
search_terms = 'astrazeneca'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"India" within:1000km').get_items()):
    if i > 100000:
        break
    #declare the attributes to be returned
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [4]:
tweets_df2

,Datetime,Tweet Id,Text,Username
0,2022-02-10 22:31:08+00:00,1491902581794353157,AstraZeneca sees $4B in COVID vaccine sales as...,NewDelhiTimes
1,2022-02-10 21:15:00+00:00,1491883421781700613,"Covid Product Sales, Profit Margins Would Drop...",CNNnews18
2,2022-02-10 20:05:14+00:00,1491865865570373637,"@JNJNews, @Roche, and @nvidia accounts for 52....",Saksheepandey4
3,2022-02-10 18:33:02+00:00,1491842664018239491,AstraZeneca warns of falling Covid treatment s...,suknmk
4,2022-02-10 17:52:30+00:00,1491832461822926848,AstraZeneca forecasts higher 2022 sales after ...,dn_rath
...,...,...,...,...
4349,2020-12-07 10:15:03+00:00,1335890559978749952,#SerumInstitute Seeks #DCGI Approval For Emerg...,UtkarshV_BJP
4350,2020-12-07 06:28:42+00:00,1335833595609419776,#Serum #Institute of #India ( #SII) in #Pune h...,thenewsroomnow
4351,2020-12-05 07:17:32+00:00,1335121109440557056,Anti-vaccine conspiracies will use this now to...,aarishc
4352,2020-12-02 04:56:22+00:00,1333998420139229189,Wonder how much it will cost for the governmen...,vikrammahajan
4353,2020-12-01 15:22:52+00:00,1333793697721270276,@NeerajCNBC @CNBC_Awaaz Its now deadly war bet...,birlalalit

In [5]:
tweets_df2.to_csv("../data/India/vaccination/astrazeneca.csv", index = False)

In [38]:
tweets_list = []

# search terms
search_terms = 'serum institute india'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"London" within:100km').get_items()):
    if i > 10000:
        break
    #declare the attributes to be returned
    tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [44]:
tweets_df

,Datetime,Tweet Id,Text,Username
0,2022-02-10 17:49:25+00:00,1491831687667494916,@soutikBBC Bulk of it produced by Serum Instit...,rpfrombushey
1,2022-02-10 12:57:43+00:00,1491758276274499584,Indiaâ€™s Serum Instituteâ€™s partnership with UK ...,MarieLo10910105
2,2022-02-06 11:27:30+00:00,1490286021031956488,Novavax and Serum Institute of India File for ...,midkentforbrit1
3,2021-04-25 18:18:51+00:00,1386384225545465860,@adil_3 @zarahsultana It's a good thing the Se...,robertwoolley
4,2021-03-03 08:19:32+00:00,1367026844214595593,#UK to get 10 million AstraZeneca COVID-19 vac...,BritishHeraldUK
5,2021-01-30 21:09:34+00:00,1355624216402350081,"Coronavirus | Novavax vaccine, to be made by S...",StigmabaseO
6,2021-01-22 00:19:28+00:00,1352410516413706245,Disgusting that South Africa have to pay more ...,GoonerKal
7,2021-01-16 10:12:36+00:00,1350385456471568385,@the_hindu Research of vaccine was done by Oxf...,sksingh56
8,2020-12-28 13:02:46+00:00,1343542911657521153,India's Serum Institute expects approval for A...,avirvisva

In [45]:
tweets_df.to_csv("../data/India/vaccination/serum_institute_india.csv", index = False)