snscrape

Ref: https://github.com/JustAnotherArchivist/snscrape

In [3]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

Scraping tweets from a text search query

Using the code below, we are scraping 100 tweets between June 14, 2020, and August 31, 2021,
with the keywords 'SSR Bollywood'.

I then pulled attributes DateTime, tweet id, text, and username from the tweet objects.

In [4]:
# Creating list to append tweet data to
tweets_list2 = []

# search terms
search_terms = 'astrazeneca '

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"Sydney" within:1000km').get_items()):
    if i > 100000:
        break
    #declare the attributes to be returned
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [5]:
tweets_df2

,Datetime,Tweet Id,Text,Username
0,2022-02-10 23:15:42+00:00,1491913797912596480,Finally the TGA has approved the Astrazeneca b...,DrewWoodford
1,2022-02-10 23:13:17+00:00,1491913191449718788,COVID: AstraZeneca booster approved for adults...,JamesConnor66
2,2022-02-10 22:06:54+00:00,1491896484932976646,So I’m uptodate as I’ve had my third shot ….....,david89293299
3,2022-02-10 21:16:10+00:00,1491883714351362048,AstraZeneca falls to loss despite Covid vaccin...,AsiaPacToday
4,2022-02-10 19:09:06+00:00,1491851741020753920,TGA อนุมัติ AstraZeneca เป็นวัคซีนบูสเตอร์เข็ม...,strongly551
...,...,...,...,...
3359,2020-12-11 20:22:22+00:00,1337492944329195521,OXFORD + RUSSIA VACCINES TO TEST COMBINED VACC...,edotedge
3360,2020-12-11 07:57:21+00:00,1337305455136108545,$AZN.PLC Astrazeneca Says Signed Final Agreeme...,joe31756
3361,2020-12-10 20:33:13+00:00,1337133290214490112,9 out of 10 people in poor countries are going...,AmnestyNZ
3362,2020-12-09 07:30:21+00:00,1336573886838652929,"And there it is, the first vaccine developer @...",lionmanxx18
3363,2020-12-08 08:10:50+00:00,1336221688002801664,$AZN.PLC AstraZeneca : Morgan Stanley raises p...,joe31756

In [6]:
tweets_df2.to_csv("../data/Australia/astrazeneca.csv", index = False)

In [22]:
tweets_list = []

# search terms
search_terms = 'janssen'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"Sydney" within:1000km').get_items()):
    if i > 10000:
        break
    #declare the attributes to be returned
    tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [23]:
tweets_df

,Datetime,Tweet Id,Text,Username
0,2022-02-10 23:45:22+00:00,1491921264658694145,@JukeNFT legit?,dodobrowser
1,2022-02-10 23:44:52+00:00,1491921139219582976,@UndeadBlocks @gemma22864259 @scarson45 @its_l...,dodobrowser
2,2022-02-10 20:42:39+00:00,1491875280025427968,"@azucarRoc After you beat them, I think you’ll...",janssen4444
3,2022-02-10 13:22:22+00:00,1491764480120098817,"this sudden focus on HIV testing, still isn’t ...",WorldOfMarkyD
4,2022-02-10 13:12:53+00:00,1491762093607256068,@chrisJcsgo @CplDocktor @priusOBS @JakeSucky O...,SallyMGibbson
...,...,...,...,...
148,2021-02-28 03:23:04+00:00,1365865072023642113,US FDA Issues Emergency Use Authorization for ...,martinfrogers
149,2021-02-17 13:11:32+00:00,1362026898918793218,I'm still such a big fan of X-Men: The Last St...,Shuttlecock
150,2021-01-18 05:08:09+00:00,1351033616332165121,"Astra-Zeneca and Pfizer, Janssen- produce, I b...",NannySaysNah
151,2021-01-13 01:43:31+00:00,1349170178567798786,"@AndreasKullman4 @DanielBleakley ""The new agre...",BeauGiles
152,2020-12-03 03:43:31+00:00,1334342474974732290,@BarryCPearson We get Pfizer in March as we ha...,MaureenStroud

In [24]:
tweets_df.to_csv("../data/Australia/janssen.csv", index = False)