snscrape

Ref: https://github.com/JustAnotherArchivist/snscrape

In [2]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

Scraping tweets from a text search query

Using the code below, we are scraping 100 tweets between June 14, 2020, and August 31, 2021,
with the keywords 'SSR Bollywood'.

I then pulled attributes DateTime, tweet id, text, and username from the tweet objects.

In [19]:
# Creating list to append tweet data to
tweets_list2 = []

# search terms
search_terms = 'pfizer'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"Sydney" within:1000km').get_items()):
    if i > 100000:
        break
    #declare the attributes to be returned
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [20]:
tweets_df2

,Datetime,Tweet Id,Text,Username
0,2022-02-10 23:55:14+00:00,1491923744918740993,@prudinx I had Pfizer. Pretty much the same de...,DamienShortal
1,2022-02-10 23:46:25+00:00,1491921529939980290,@bittern36921585 @CNCIB @abcnews The creator w...,WARegionalTrees
2,2022-02-10 23:45:14+00:00,1491921230567739392,"Didn't Albert Bourla aka Pfizer CEO, already s...",Mr_Short_Stop
3,2022-02-10 23:42:14+00:00,1491920473445310465,For anyone wanting to read the released docume...,trelisemcbain
4,2022-02-10 23:40:35+00:00,1491920058028748800,@mikeymikester @abcnews So Pfizer etc won‚Äôt re...,WARegionalTrees
...,...,...,...,...
12346,2020-12-02 07:50:57+00:00,1334042355456827395,Wow.\n\nBritain approves Pfizer-BioNTech COVID...,sloanefather
12347,2020-12-02 07:34:50+00:00,1334038301280387072,#BREAKING The UK has become the first country ...,ConnorDStirling
12348,2020-12-02 07:25:54+00:00,1334036050012848129,Wow üëèüëèüëè @RackMada @horowitz_b @markfebbraio \n...,nir_eynon
12349,2020-12-02 07:19:17+00:00,1334034388066025472,GOOD MORNING TO THE UK ONLY!!!!!! Pop the Pfiz...,chadirl
12350,2020-12-01 21:53:05+00:00,1333891898516205570,@MatureAmericans @SecAzar @realDonaldTrump Pfi...,GeorgeManka

In [21]:
tweets_df2.to_csv("../data/Australia/pfizer2.csv", index = False)

In [22]:
tweets_list = []

# search terms
search_terms = 'janssen'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"Sydney" within:1000km').get_items()):
    if i > 10000:
        break
    #declare the attributes to be returned
    tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [23]:
tweets_df

,Datetime,Tweet Id,Text,Username
0,2022-02-10 23:45:22+00:00,1491921264658694145,@JukeNFT legit?,dodobrowser
1,2022-02-10 23:44:52+00:00,1491921139219582976,@UndeadBlocks @gemma22864259 @scarson45 @its_l...,dodobrowser
2,2022-02-10 20:42:39+00:00,1491875280025427968,"@azucarRoc After you beat them, I think you‚Äôll...",janssen4444
3,2022-02-10 13:22:22+00:00,1491764480120098817,"this sudden focus on HIV testing, still isn‚Äôt ...",WorldOfMarkyD
4,2022-02-10 13:12:53+00:00,1491762093607256068,@chrisJcsgo @CplDocktor @priusOBS @JakeSucky O...,SallyMGibbson
...,...,...,...,...
148,2021-02-28 03:23:04+00:00,1365865072023642113,US FDA Issues Emergency Use Authorization for ...,martinfrogers
149,2021-02-17 13:11:32+00:00,1362026898918793218,I'm still such a big fan of X-Men: The Last St...,Shuttlecock
150,2021-01-18 05:08:09+00:00,1351033616332165121,"Astra-Zeneca and Pfizer, Janssen- produce, I b...",NannySaysNah
151,2021-01-13 01:43:31+00:00,1349170178567798786,"@AndreasKullman4 @DanielBleakley ""The new agre...",BeauGiles
152,2020-12-03 03:43:31+00:00,1334342474974732290,@BarryCPearson We get Pfizer in March as we ha...,MaureenStroud

In [24]:
tweets_df.to_csv("../data/Australia/janssen.csv", index = False)