snscrape

Ref: https://github.com/JustAnotherArchivist/snscrape

In [1]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

Scraping tweets from a text search query

Using the code below, we are scraping 100 tweets between June 14, 2020, and August 31, 2021,
with the keywords 'SSR Bollywood'.

I then pulled attributes DateTime, tweet id, text, and username from the tweet objects.

In [13]:
# Creating list to append tweet data to
tweets_list2 = []

# search terms
search_terms = 'novavax'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"London" within:1000km').get_items()):
    if i > 10000:
        break
    #declare the attributes to be returned
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [14]:
tweets_df2

,Datetime,Tweet Id,Text,Username
0,2022-02-10 23:18:34+00:00,1491914517995044866,Novavax annonce une efficacité de 80% pour son...,123_INFO_FR
1,2022-02-10 23:17:23+00:00,1491914222380457985,@Markus_Soeder Vielleicht sollte man mit allde...,HJKRedakteur
2,2022-02-10 23:05:09+00:00,1491911144713461768,Covid-19: Novavax revendique une efficacité de...,123_INFO_FR
3,2022-02-10 23:02:26+00:00,1491910460123324418,Covid-19: Novavax revendique une efficacité de...,BFMTV
4,2022-02-10 22:52:23+00:00,1491907931595587584,(FR) Novavax annonce une efficacité de 80% pou...,123_INFO_BE
...,...,...,...,...
2442,2020-12-03 13:49:16+00:00,1334494917155041282,Reino Unido compra 60 millones de dosis de vac...,mnuclear1
2443,2020-12-02 17:43:57+00:00,1334191588411645954,@MarkYoung23 Would advise consultation w their...,shanemuk
2444,2020-12-02 16:10:38+00:00,1334168105703133184,Lovely to see this local @KingsCollegeNHS trib...,alison_firth
2445,2020-12-02 15:02:21+00:00,1334150922650398722,All these people talking about not having the ...,youngin_uk
2446,2020-12-01 23:01:27+00:00,1333909103194886144,@CommanderMP Which one are you getting? I’m on...,antisyzygy

In [15]:
tweets_df2.to_csv("../data/UK/novavax.csv", index = False)

In [19]:
tweets_list = []

# search terms
search_terms = 'oxford vaccine'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"London" within:100km').get_items()):
    if i > 10000:
        break
    #declare the attributes to be returned
    tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [20]:
tweets_df

,Datetime,Tweet Id,Text,Username
0,2022-02-10 22:58:21+00:00,1491909433483534340,OXFORD BLUES. I'm having to deal with a challe...,YardleyShooting
1,2022-02-10 15:55:37+00:00,1491803046937980928,@KwasiKwarteng @UKAEAofficial If it ever comes...,gary_worden
2,2022-02-10 15:01:46+00:00,1491789494445432847,BioNTech vaccine only c. 35% effective against...,robblackie_oo
3,2022-02-10 02:09:44+00:00,1491595207472779264,"""The Times view on criticism of the Oxford-Ast...",DianaStevenson2
4,2022-02-09 21:14:27+00:00,1491520897563471879,@doctor_oxford If you have the time to give a ...,hskensington
...,...,...,...,...
685,2020-12-02 15:33:46+00:00,1334158826296258561,Oxford vaccine really needs to come onside as ...,Ch1Hudson
686,2020-12-02 12:15:55+00:00,1334109037105909761,#Pfizer #CovidVaccine #oxfordvaccine @UniofOxf...,aggala
687,2020-12-02 08:43:13+00:00,1334055508739829761,Just now pray Oxford vaccine comes quickly,Ch1Hudson
688,2020-12-02 08:38:26+00:00,1334054306966884353,@n_rh1992 Yeah hopefully. The Govt has already...,Chris_CPH
689,2020-12-01 10:36:47+00:00,1333721702572953600,"NEW: Scandal-hit ""Oxford"" Coronavirus vaccine ...",afshinrattansi

In [21]:
tweets_df.to_csv("../data/UK/oxford.csv", index = False)