snscrape

Ref: https://github.com/JustAnotherArchivist/snscrape

In [1]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

Scraping tweets from a text search query

Using the code below, we are scraping 100 tweets between June 14, 2020, and August 31, 2021,
with the keywords 'SSR Bollywood'.

I then pulled attributes DateTime, tweet id, text, and username from the tweet objects.

In [41]:
# Creating list to append tweet data to
tweets_list2 = []

# search terms
search_terms = 'covishield'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"India" within:1000km').get_items()):
    if i > 100000:
        break
    #declare the attributes to be returned
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [42]:
tweets_df2

,Datetime,Tweet Id,Text,Username
0,2022-02-10 15:30:17+00:00,1491796672489594886,Worn mask for way too much time which has made...,She_Says_It_
1,2022-02-10 15:06:14+00:00,1491790620876161028,Date-11/02/2022\n\nTime - 9.00am to 5.00pm\n\n...,mybmcWardRC
2,2022-02-10 14:32:27+00:00,1491782116828323848,@EdzardErnst All who took covishield vaccine g...,drmitras
3,2022-02-10 14:13:11+00:00,1491777268854964227,SW delhi has at least 28102 new slots availabl...,CovidvaxDEL
4,2022-02-10 13:50:54+00:00,1491771663134126086,@Thamizhan74 This is less safe I think- the Ja...,prabirkc
...,...,...,...,...
10956,2020-12-07 03:56:48+00:00,1335795367254716417,बड़ी खबर : कोरोना वैक्सीन Covishield के लिए सी...,BhaiyajiCom
10957,2020-12-06 23:08:40+00:00,1335722856714391554,सीरम इंस्टीट्यूट ने Covishield के आपात इस्तेमा...,itsparvezsagar
10958,2020-12-06 18:43:33+00:00,1335656138310701062,#Good_news\nSerum Institute seeks emergency us...,PrabeenSahu3
10959,2020-12-03 08:22:21+00:00,1334412645085036544,UK is getting Pfizer's COVID-19 vaccine next w...,sajidalimarwadi
10960,2020-12-03 03:24:08+00:00,1334337595568840704,Pfizer vaccine is not available immediately to...,svmurthy

In [43]:
tweets_df2.to_csv("../data/India/vaccination/covishield.csv", index = False)

In [38]:
tweets_list = []

# search terms
search_terms = 'serum institute india'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2020-12-01 until:2022-02-11 near:"London" within:100km').get_items()):
    if i > 10000:
        break
    #declare the attributes to be returned
    tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username',])

In [44]:
tweets_df

,Datetime,Tweet Id,Text,Username
0,2022-02-10 17:49:25+00:00,1491831687667494916,@soutikBBC Bulk of it produced by Serum Instit...,rpfrombushey
1,2022-02-10 12:57:43+00:00,1491758276274499584,India’s Serum Institute’s partnership with UK ...,MarieLo10910105
2,2022-02-06 11:27:30+00:00,1490286021031956488,Novavax and Serum Institute of India File for ...,midkentforbrit1
3,2021-04-25 18:18:51+00:00,1386384225545465860,@adil_3 @zarahsultana It's a good thing the Se...,robertwoolley
4,2021-03-03 08:19:32+00:00,1367026844214595593,#UK to get 10 million AstraZeneca COVID-19 vac...,BritishHeraldUK
5,2021-01-30 21:09:34+00:00,1355624216402350081,"Coronavirus | Novavax vaccine, to be made by S...",StigmabaseO
6,2021-01-22 00:19:28+00:00,1352410516413706245,Disgusting that South Africa have to pay more ...,GoonerKal
7,2021-01-16 10:12:36+00:00,1350385456471568385,@the_hindu Research of vaccine was done by Oxf...,sksingh56
8,2020-12-28 13:02:46+00:00,1343542911657521153,India's Serum Institute expects approval for A...,avirvisva

In [45]:
tweets_df.to_csv("../data/India/vaccination/serum_institute_india.csv", index = False)